use std::collections::HashMap;

fn main() {
    // TODO: parse hashmap from json/toml
    #[rustfmt::skip]
    let unicode_map: HashMap<&str, &str> = HashMap::from_iter([
        (r#"┬─┬ノ( º _ ºノ)"#, "Table back"),
        (r#"Σ(▼□▼メ)"#, "Anger"),
        (r#"ლ(ಠ益ಠ)ლ"#, "why"),
        (r#"-_-;"#, "Sweat Drop"),
        (r#"(¬_¬")"#, "Annoyed"),
        (r#"(⊃‿⊂)"#, "Anticipation"),
        (r#"(シ_ _)シ"#, "sorry"),
        (r#"(^^)//"#, "Applause"),
        (r#"( `_)乂(_' )"#, "Arm wrestle"),
        (r#"(；一_一)"#, "Ashamed"),
        (r#"(⌒ ͜ʖ⌒)b"#, "Attentive"),
        (r#"/|\( ;,; )/|\"#, "Bat"),
        (r#"ಥ_ಥ"#, "cry"),
        (r#"（　＾＾）人（＾＾　）"#, "Best Buds"),
        (r#"└(^o^ )Ｘ( ^o^)┘"#, "Best buddies"),
        (r#"(￣▼￣)"#, "Big Grin"),
        (r#"ヽ(⌐■_■)ノ♪♬"#, "Boogie"),
        (r#"ヾ(｀ε´)ﾉ"#, "Boo"),
        (r#"<( ･ｪ-)<}"#, "archer"),
        (r#"＝( ^o^)ノ___ｏ"#, "Bowling"),
        (r#"(ó ì_í)=óò=(ì_í ò)"#, "Bro fist"),
        (r#"(*^o^)人(^o^*)"#, "highfive"),
        (r#"Ƹ̵̡Ӝ̵̨̄Ʒ"#, "Butterfly"),
        (r#"＼(^o)(^0^)(o^)／"#, "Caroling"),
        (r#"＼(＾O＾)／"#, "Celebrate"),
        (r#"ᕕ( ᐛ )ᕗ"#, "happydance"),
        (r#"ᘛ⁐̤ᕐᐷ"#, "Chameleon"),
        (r#"(○｀д´)ﾉｼ Σ(っﾟДﾟ)っ"#, "Chasing"),
        (r#"〜〜(／￣▽)／　〜ф"#, "Chasing Butterfly"),
        (r#"^)_(^"#, "Chubby"),
        (r#"(￣ー￣)//””"#, "Clap"),
        (r#"╹﹏╹"#, "Cold"),
        (r#"(。。;)＼(-_-)"#, "comfort"),
        (r#"¯\(°_o)/¯"#, "shrugconfused"),
        (r#"｢(ﾟﾍﾟ)"#, "Confused"),
        (r#"(◐‿◑)"#, "Crazy"),
        (r#"(¬‿¬)"#, "Cunning"),
        (r#"┌|°з°|┘"#, "Cutting a rug"),
        (r#"(╬☉Д⊙ฺ)"#, "Cyborg"),
        (r#"♪┏(・o･)┛♪"#, "dance"),
        (r#"(｡▼皿▼)"#, "Darth Vader"),
        (r#"(#×_×)"#, "Dead"),
        (r#"✖‿✖"#, "Dead person"),
        (r#"(▀̿Ĺ̯▀̿ ̿)"#, "Deal with it"),
        (r#"(ಥ﹏ಥ)"#, "sadcry"),
        (r#"ಠ_ಠ"#, "look"),
        (r#"（￣へ￣）"#, "Discontent"),
        (r#"(*￣m￣)"#, "Dissatisfied"),
        (r#"༼ ༎ຶ ෴ ༎ຶ༽"#, "Distraught"),
        (r#"◤◡ᴥ◡◥"#, "Dog"),
        (r#"V●ᴥ●V"#, "Doggy"),
        (r#"(_ _)..ooOO"#, "Dreaming"),
        (r#"( -_-)旦~"#, "coffee"),
        (r#"♥‿♥"#, "amore"),
        (r#"(๑≖ิิ益≖ิ๑)"#, "Evil Laugh"),
        (r#"ヽ(★ω★)ノ"#, "Excited"),
        (r#"†_(ﾟｰﾟ*)β"#, "Exorcism"),
        (r#"(+.+)(-.-)(_ _)"#, "Falling Asleep"),
        (r#"＼(｀0´)／"#, "Fed Up"),
        (r#"(ง •̀_•́)ง"#, "fistup"),
        (r#"(ง •̀ゝ•́)ง"#, "Fighting"),
        (r#"ϵ( 'Θ' )϶"#, "Fish"),
        (r#"ᕦ(ò_óˇ)ᕤ"#, "Flex"),
        (r#"(╮°-°)╮┳━━┳ ( ╯°□°)╯ ┻━━┻"#, "FlipTable"),
        (r#"(╯°益°)╯彡┻━┻"#, "FlipTable anger"),
        (r#"(╯°□°）╯︵ ┻━┻"#, "Flip"),
        (r#"ヽ(´Д｀ヽミノ´Д｀)ノ"#, "Frantic"),
        (r#"ヽ(ﾟДﾟ)ﾉ"#, "Freak Out"),
        (r#"(／。＼)"#, "Frightened"),
        (r#":(¦)"#, "Frog"),
        (r#"(ò_ó)"#, "Furious"),
        (r#"(((༼•̫͡•༽)))"#, "Ghost"),
        (r#"(´・ω・)っ由"#, "Gift"),
        (r#"(о＾ω＾о)"#, "Giggling"),
        (r#"༼ つ ◕_◕ ༽つ"#, "Gimme"),
        (r#"(;-_-)ノ"#, "Giving up"),
        (r#"＼（＾ ＾）／"#, "Glad"),
        (r#"｡◕‿◕｡"#, "Gleeful"),
        (r#"(´ー｀)┌ﾌｯ"#, "Golf Clap"),
        (r#"＼（～Ｏ～）／"#, "ohaiyou"),
        (r#"♪(●′▽`)ﾉ"#, "konn"),
        (r#"(^ _ ^)/~~"#, "Goodbye"),
        (r#"◖ර◞ʖ◟ර◗"#, "Grandma"),
        (r#"└(^o^)┐"#, "Grooving"),
        (r#"￢o(￣-￣ﾒ)"#, "Gun"),
        (r#"(°̥̥̥̥̥̥̥̥ᴗ°̥̥̥̥̥̥̥̥)"#, "Happy cryin"),
        (r#"(( ＿ ＿)☆ ≡〇"#, "Header"),
        (r#"(∿°○°)∿ ︵ ǝʌol"#, "Heartbroken"),
        (r#"┬┴┬┴┤･ω･)ﾉ"#, "Hiding"),
        (r#"( ˇ෴ˇ )"#, "Hipster"),
        (r#"( ｀皿´)｡ﾐ/"#, "Hitting"),
        (r#"(ﾉﾟ0ﾟ)ﾉ~	Yoo-"#, "Hoo"),
        (r#"o(^^o)(o^^)o"#, "Hopeful"),
        (r#"┗(･ω･;)┛"#, "HowIKnow"),
        (r#"(っ⌒‿⌒)っ"#, "Hug"),
        (r#"⊂((・▽・))⊃"#, "Hug me"),
        (r#"(>^_^)><(^o^<)"#, "Hugging"),
        (r#"[•.•ิ]"#, "Huh"),
        (r#"┗( ●-﹏ ｀｡)づ"#, "Hurt"),
        (r#"(♥_♥)"#, "In Love"),
        (r#"♫.(◠౪◠).♫"#, "Jamming"),
        (r#"⎰≀.☮-☮≀⎰"#, "John Lennon"),
        (r#"( ｀o´)_θ☆"#, "Kicking"),
        (r#"(っ^‿^)っ"#, "Kirby"),
        (r#"(ﾉ´ з `)ノ"#, "Kiss"),
        (r#"( ˘ ³˘)♥"#, "Kiss me"),
        (r#"(* ￣)(￣ *)"#, "Kissing"),
        (r#"(=^･ｪ･^=)"#, "Kitty"),
        (r#"⋟^≏^⋞"#, "Kitty Cat"),
        (r#"ʕ •ᴥ•ʔ"#, "Koala"),
        (r#"／人◕ ‿‿ ◕人＼"#, "Kyu"),
        (r#"m( ﾟ皿ﾟ)m★━━"#, "Laser"),
        (r#"(‾ʖ̫‾)"#, "Lethargic"),
        (r#"(ɔˆ ³(ˆ⌣ˆc)"#, "couple"),
        (r#"o(>< )o⌒*"#, "Mad"),
        (r#"(∩｀-´)⊃━☆ﾟ.*･｡ﾟ"#, "Magic"),
        (r#"（＾～＾）"#, "Meh"),
        (r#"ヽ（´ー｀）┌"#, "Mellow"),
        (r#"@( o･ω･)@"#, "Monkey"),
        (r#"ಠ_ರೃ"#, "Monocle"),
        (r#"( ￣┏＿┓￣)"#, "Mustache"),
        (r#"( --)/ ==卍"#, "Ninja Star"),
        (r#"(￣ー￣（＿　＿（"#, "Nodd"),
        (r#"[^._.^]ﾉ彡"#, "Nyan Cat"),
        (r#"L(´□｀L)	"#, "Oh No"),
        (r#"(ﾉ-o-)ﾉ 中"#, "Hammer Throw"),
        (r#"(>_<)"#, "Pain"),
        (r#"(。･_･)ノ”【】"#, "Paint"),
        (r#"◖㈠ ω ㈠◗"#, "Panda"),
        (r#"\\(<.<|>.>)//"#, "Panic"),
        (r#"✌(◕‿-)✌"#, "Peace"),
        (r#"(/ω･＼)"#, "Peering"),
        (r#"༼ঢ_༽ঢ༽"#, "Perplexed"),
        (r#"ε-(´・｀) ﾌ"#, "Phew"),
        (r#"(─‿‿─)"#, "Pleased"),
        (r#"(☞ﾟヮﾟ)☞"#, "Pointing"),
        (r#"(*・)σσ(*゜O゜)"#, "Poke"),
        (r#"ʕ•͡ᴥ•ʔ"#, "bear"),
        (r#"(╯˘ -˘ )╯"#, "Pray"),
        (r#"（人’∀’）"#, "Precious"),
        (r#"( ° ᴗ°)~ð"#, "Proposal"),
        (r#"ヘ（。□°）ヘ"#, "Psycho"),
        (r#"ヽ( ★ω★)ノ"#, "Pumped"),
        (r#"（。_°☆＼(- – )"#, "hit"),
        (r#"(。_°)☆"#, "Punched"),
        (r#"(o￣∇￣)=◯)`ν゜)･"#, "Punching"),
        (r#"U＾ェ＾U"#, "Puppy"),
        (r#"∊♡_ᴥ_♡∍"#, "Puppy Love"),
        (r#"Q('.'Q)"#, "Put Em Up"),
        (r#"┬─┬ノ( º _ ºノ)"#, "Table Back"),
        (r#"「(°ヘ°)"#, "Puzzled"),
        (r#"( ´-ω･)︻┻┳══━一"#, "Rifle"),
        (r#"(ɔ˘з˘)ɔ"#, "Romantic"),
        (r#"ε=┏( >_<)┛"#, "Run"),
        (r#"←～（o ｀▽´ )oΨ"#, "Satan"),
        (r#"(▰˘◡˘▰)"#, "Satisfied"),
        (r#"(☄ฺ◣д◢)☄ฺ"#, "Scaring"),
        (r#"(╯‵Д′)╯"#, "Scary"),
        (r#"ಠᴗಠ"#, "Scheming"),
        (r#"<(;￣ ･￣)"#, "Scratching"),
        (r#"ᶘ ᵒᴥᵒᶅ"#, "Seal"),
        (r#"⊙▂⊙"#, "Shocked"),
        (r#"(★▼▼)o┳*--"#, "Shooting"),
        (r#"┻━┻ ︵ ¯\ (ツ)/¯ ︵ ┻━┻"#, "Shrug flip table"),
        (r#"¯\_▐ ☯ ︿ ☯ ▐_/¯"#, "Shrug sad"),
        (r#"¯\_(ツ)_/¯"#, "shrug"),
        (r#"（/｡＼)"#, "Shy"),
        (r#"[ ± _ ± ]"#, "Sick"),
        (r#"(•͡.•͡)"#, "Skeptic"),
        (r#"(；^＿^)ッ☆(　゜o゜)"#, "Slapping"),
        (r#"(∪｡∪)｡｡｡zzZ"#, "Sleeping"),
        (r#"(- o - ) zzZ ☽"#, "Sleepy"),
        (r#"(ʘ‿ʘ)"#, "Smile"),
        (r#"( ͡° ͜ʖ ͡°)"#, "Smiling"),
        (r#"(｡♥‿♥｡)"#, "Smitten"),
        (r#"◯０o。(ー。ー)y"#, "vaping"),
        (r#"(づ￣ ³￣)づ"#, "Smooch"),
        (r#"( ´-ω･)︻┻┳══━一"#, "Sniper"),
        (r#"┬┴┬┴┤(･_├┬┴┬┴"#, "hidewall"),
        (r#"❆❅❉"#, "Snowing"),
        (r#"(ू˃̣̣̣̣̣̣︿˂̣̣̣̣̣̣ ू)"#, "Sobby"),
        (r#"੯ू•́ू ໒꒱⁼³₌₃"#, "Sonic"),
        (r#"|∴め ϖ め∴|"#, "SpongeBob"),
        (r#"ε=ε=ε=┌(๑ʘ∀ʘ)┘"#, "Sprint"),
        (r#"<コ:彡"#, "Squid"),
        (r#"|̲̅̅●̲̅̅|̲̅̅=̲̅̅|̲̅̅●̲̅̅|"#, "radio"),
        (r#"─=≡Σ(([ ⊐•̀⌂•́]⊐"#, "Superhero"),
        (r#"（￣□￣；）"#, "ge"),
        (r#"( ｣｡╹o╹｡)｣"#, "Surprised arms"),
        (r#"（｡◕ o ◕｡）"#, "Surprised glee"),
        (r#"(´>_●)メ(●_<｀)"#, "Sword Fighting"),
        (r#"┬─┬︵/(.□.)╯"#, "Table Flips You"),
        (r#"༼ つ ◕_◕ ༽つ"#, "Take my energy"),
        (r#"(๑╹ڡ╹๑)"#, "Tasty"),
        (r#"＼(-_- )"#, "sankyu"),
        (r#"(*・_・)ノ⌒*"#, "litter"),
        (r#"---(o_　_)o"#, "Tripping"),
        (r#"（￣～￣）"#, "Unimpressed"),
        (r#"{{|└(>o< )┘|}}"#, "Up In Arms"),
        (r#"(*▿▿* ƪ)"#, "Vampire"),
        (r#"(″･ิ_･ิ)っ"#, "matte"),
        (r#"且_(ﾟ◇ﾟ；)ノﾞ"#, "Waiter"),
        (r#"(:3 っ)っ"#, "Walrus"),
        (r#"( ^_^)ノ"#, "Waving"),
        (r#"(´~`)"#, "Weary"),
        (r#"(;´༎ຶД༎ຶ`)"#, "Weeping"),
        (r#"(^‿◕)"#, "Wink"),
        (r#"(∩｀-´)⊃━☆ﾟ.*･｡ﾟ"#, "Wizard"),
        (r#"(´╹〽╹`)"#, "Worried"),
        (r#"(╯•﹏•╰)"#, "Worried arms"),
        (r#"(◍•﹏•)"#, "Worried simple"),
        (r#"＿〆(。。)"#, "Writing"),
        (r#"ヾ(*￣O￣)ツ"#, "Yelling"),
        (r#"(☉__☉”)"#, "Yikes"),
        (r#"(っ˘ڡ˘ς)"#, "Yummy"),
        (r#"[¬º-°]¬"#, "Zombie"),
    ]);

    println!("const ucis_symbol_t ucis_symbol_table[] = UCIS_TABLE(");
    let unicode_count = unicode_map.len();
    for (idx, (k, name)) in unicode_map.into_iter().enumerate() {
        let mut n = name.to_lowercase();
        n.retain(|c| c != ' ');
        print!("\tUCIS_SYM(\"{}\", ", n);
        let len = k.chars().count();
        for (idx, b) in k.chars().enumerate() {
            print!("{:#06X}", b as u32);
            if idx + 1 < len {
                print!(",");
            }
        }
        print!(")");
        if idx + 1 < unicode_count {
            print!(",");
        }
        print!(" /* {k} */\n");
    }
    println!(")");
}
